# Default values for v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.27.3

autoscaling:
  hpa:
    enabled: false

externalSecret:
  enabled: false

deployment:
  enabled: false

ingress:
  enabled: false

service:
  enabled: false

serviceAccount:
  enabled: false
