# Default values for v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: myrepo
  tag: v1

autoscaling:
  enabled: false

externalSecret:
  enabled: false

deployment:
  enabled: false

ingress:
  enabled: false

service:
  enabled: false

serviceAccount:
  enabled: false
