{{- if and (.Values.externalSecret).enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
{{- include "lib.metadata" . }}
spec:
  externalSecretName: {{ include "lib.instanceName" . }}
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .Values.namespace | default .Release.Namespace }}
  externalSecretSpec:
    secretStoreRef:
      name: awssecretsmanager
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: {{ include "lib.instanceName" . }}
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: {{ include "lib.instanceName" . }}
{{- end }}