{{- $hpa := (.Values.autoscaling).hpa }}
{{- if and $hpa.enabled (.Values.deployment).enabled (coalesce false $hpa.targetCPUUtilizationPercentage $hpa.targetMemoryUtilizationPercentage) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
{{- include "lib.metadata" . }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.apiVersion | default "apps/v1" }}
    kind: {{ .Values.kind | default "Deployment" }}
    name: {{ include "lib.instanceName" . }}
  minReplicas: {{ $hpa.minReplicas | default 1 }}
  maxReplicas: {{ $hpa.maxReplicas | default 3 }}
  metrics:
  {{- if $hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $hpa.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}