{{- if and (.Values.serviceAccount).enabled }}
apiVersion: v1
kind: ServiceAccount
{{- include "lib.metadata" . }}
  {{- with (.Values.serviceAccount).annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}