{{- if and (.Values.service).enabled (.Values.deployment).ports }}
apiVersion: v1
kind: Service
{{- include "lib.metadata" . }}
  {{- with (.Values.service).annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  {{- range $name, $port := (.Values.deployment).ports }}
  - name: {{ $name }}
    port: {{ $port }}
    targetPort: {{ $name }}
    protocol: TCP
  {{- end }}
  selector:
  {{- include "lib.selectorLabels" . | nindent 4 }}
{{- end }}